### ISSUE TITLE
Unmet dependency

### ISSUE THREAD

**Issue by lordnynex** [Stouts/Stouts.wale#11]
Hello,

I've noticed on my systems (ubuntu 14.04) that the python modules requests and six are not new enough for one of wal-e's dependencies (I'm not sure which). 

I've temporarily worked around this issue by creating a pre-task to 
```yaml
- pip: name=requests state=latest
- pip: name=six state=latest
```

**Comment by klen** [comment]
Shoul be fixed now. Thank you for the report.
